# Generated by Django 4.1.3 on 2022-12-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(related_name='Category', to='shop.category'),
        ),
    ]
