# Generated by Django 4.1.3 on 2022-12-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='shop.subcategory'),
            preserve_default=False,
        ),
    ]
