# Generated by Django 4.1.3 on 2022-12-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.CharField(max_length=16),
        ),
    ]
